"use client";

import { useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronDown, Download, FileSpreadsheet, FileText, LoaderCircle, Play, Plus, RefreshCw, ShieldCheck, Trash2, Upload, XCircle } from "lucide-react";
import type { AuditSummary, ColumnMapping, ComparisonRow, ComparisonStatus, InventoryRow, InventoryWorkbook, InvoiceFile, InvoiceLine } from "@/types/audit";
import { extractPdfText } from "@/lib/pdf/extractPdfText";
import { parseInvoice } from "@/lib/pdf/parseInvoice";
import { autoMap, mapInventory, readInventoryFile } from "@/lib/excel/readInventory";
import { compareProducts, consolidateLines } from "@/lib/comparison";
import { exportAuditReport } from "@/lib/excel/exportReport";
import { parseLocaleNumber } from "@/lib/numberParser";

const statusClass: Record<string, string> = { "Procesado": "bg-emerald-100 text-emerald-800", "Válido": "bg-emerald-100 text-emerald-800", "Coincide": "bg-emerald-100 text-emerald-800", "Pendiente": "bg-slate-100 text-slate-700", "Procesando": "bg-blue-100 text-blue-800", "Revisión requerida": "bg-amber-100 text-amber-900", "Sin texto detectable": "bg-orange-100 text-orange-900", "Error": "bg-red-100 text-red-800", "Faltante": "bg-red-100 text-red-800", "Sobrante": "bg-blue-100 text-blue-800", "No encontrado": "bg-purple-100 text-purple-800", "Solo en inventario": "bg-slate-200 text-slate-800" };
const Badge = ({ children }: { children: string }) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[children] ?? "bg-slate-100"}`}>{children}</span>;
const Button = ({ children, kind = "primary", className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { kind?: "primary" | "secondary" | "danger" }) => <button className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition ${kind === "primary" ? "bg-teal-700 text-white hover:bg-teal-800" : kind === "danger" ? "border border-red-200 bg-white text-red-700 hover:bg-red-50" : "border border-slate-300 bg-white text-slate-700 hover:bg-slate-50"} ${className}`} {...props}>{children}</button>;
const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</section>;
const uid = () => crypto.randomUUID();
type AuditMode = "analyze" | "excel" | "manual";
const formatSize = (bytes: number) => bytes ? `${(bytes / 1024 / 1024).toFixed(2)} MB` : "Demo";
const money = (value: number, currency: string) => new Intl.NumberFormat("es-CR", { style: currency === "none" ? "decimal" : "currency", currency: currency === "none" ? undefined : currency, maximumFractionDigits: 2 }).format(value);

export default function Home() {
  const [mode, setMode] = useState<AuditMode | null>(null);
  const [showFinal, setShowFinal] = useState(false);
  const [manualCounts, setManualCounts] = useState<Record<string, number | undefined>>({});
  const [files, setFiles] = useState<InvoiceFile[]>([]);
  const [lines, setLines] = useState<InvoiceLine[]>([]);
  const [inventoryBook, setInventoryBook] = useState<InventoryWorkbook>();
  const [mapping, setMapping] = useState<ColumnMapping>({ code: "", description: "", quantity: "", cost: "" });
  const [inventory, setInventory] = useState<InventoryRow[]>([]);
  const [processing, setProcessing] = useState(false);
  const [concurrency, setConcurrency] = useState(3);
  const [currency, setCurrency] = useState("CRC");
  const [includeOnlyInventory, setIncludeOnlyInventory] = useState(true);
  const [tolerance, setTolerance] = useState(1);
  const [filter, setFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [fileFilter, setFileFilter] = useState("");
  const [notice, setNotice] = useState("");
  const abortRef = useRef<AbortController | undefined>(undefined);
  const pdfInput = useRef<HTMLInputElement>(null);
  const inventoryInput = useRef<HTMLInputElement>(null);

  const consolidated = useMemo(() => consolidateLines(lines), [lines]);
  const manualComparisons = useMemo<ComparisonRow[]>(() => consolidated.map((product) => {
    const count = manualCounts[product.key];
    const difference = count === undefined ? undefined : count - product.billedQuantity;
    const status = count === undefined ? "Revisión requerida" : count - product.billedQuantity === 0 ? "Coincide" : count - product.billedQuantity < 0 ? "Faltante" : "Sobrante";
    return { id: product.key, code: product.code, product: product.description, billedQuantity: product.billedQuantity, inventoryQuantity: count, difference, averagePrice: product.averagePrice, billedTotal: product.billedTotal, status, matchMethod: "Conteo manual", observation: count === undefined ? "Ingrese el conteo físico." : "" };
  }), [consolidated, manualCounts]);
  const comparisons = useMemo(() => mode === "analyze" ? [] : mode === "manual" ? manualComparisons : compareProducts(consolidated, inventory, includeOnlyInventory), [mode, manualComparisons, consolidated, inventory, includeOnlyInventory]);
  const summary = useMemo<AuditSummary>(() => ({ invoiceCount: files.length, processedCount: files.filter((f) => f.status === "Procesado").length, errorCount: files.filter((f) => f.status === "Error").length, noTextCount: files.filter((f) => f.status === "Sin texto detectable").length, extractedProducts: lines.length, consolidatedProducts: consolidated.length, billedUnits: consolidated.reduce((n, p) => n + p.billedQuantity, 0), billedTotal: consolidated.reduce((n, p) => n + p.billedTotal, 0), matches: comparisons.filter((r) => r.status === "Coincide").length, shortages: comparisons.filter((r) => r.status === "Faltante").length, surpluses: comparisons.filter((r) => r.status === "Sobrante").length, notFound: comparisons.filter((r) => r.status === "No encontrado").length, reviewRequired: lines.filter((r) => r.status === "Revisión requerida").length + comparisons.filter((r) => r.status === "Revisión requerida").length }), [files, lines, consolidated, comparisons]);
  const completed = files.filter((f) => !["Pendiente", "Procesando"].includes(f.status)).length;
  const progress = files.length ? Math.round(completed / files.length * 100) : 0;
  const insights = useMemo(() => {
    const observations: string[] = [];
    const differences = comparisons.filter((r) => ["Faltante", "Sobrante", "No encontrado"].includes(r.status)).length;
    const missingCodes = consolidated.filter((p) => !p.code).length;
    const inconsistent = files.filter((f) => { const calc = lines.filter((l) => l.fileName === f.name).reduce((n, l) => n + (l.lineTotal ?? 0), 0); return f.header?.total !== undefined && Math.abs(f.header.total - calc) > tolerance; }).length;
    const variablePrices = consolidated.filter((p) => p.maxPrice !== p.minPrice).length;
    const repeated = consolidated.filter((p) => p.invoiceCount > 1).length;
    if (differences) observations.push(`Se encontraron ${differences} productos con diferencias.`);
    if (missingCodes) observations.push(`Existen ${missingCodes} productos sin código.`);
    if (inconsistent) observations.push(`Hay ${inconsistent} facturas con totales inconsistentes.`);
    if (variablePrices) observations.push(`${variablePrices} productos aparecen con diferentes precios.`);
    if (repeated) observations.push(`${repeated} productos se repiten en múltiples facturas.`);
    if (summary.reviewRequired) observations.push(`Existen ${summary.reviewRequired} registros que requieren revisión.`);
    return observations.length ? observations : ["Los insights aparecerán conforme se procesen las facturas."];
  }, [comparisons, consolidated, files, lines, tolerance, summary.reviewRequired]);

  function selectPdfs(selected: FileList | null) {
    if (!selected) return;
    const incoming = [...selected].slice(0, Math.max(0, 200 - files.length));
    const valid = incoming.filter((file) => file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf"));
    if (valid.length !== incoming.length) setNotice("Se omitieron archivos que no son PDF.");
    setFiles((old) => [...old, ...valid.map((file) => ({ id: uid(), file, name: file.name, size: file.size, status: "Pendiente" as const }))]);
  }

  async function processOne(target: InvoiceFile, signal: AbortSignal) {
    if (!target.file) return;
    setFiles((old) => old.map((f) => f.id === target.id ? { ...f, status: "Procesando", message: "Extrayendo texto…" } : f));
    try {
      if (target.size > 50 * 1024 * 1024) throw new Error("El PDF supera el límite recomendado de 50 MB.");
      const result = await extractPdfText(target.file, signal);
      if (!result.text.trim()) {
        setFiles((old) => old.map((f) => f.id === target.id ? { ...f, file: undefined, pages: result.pages, status: "Sin texto detectable", processedAt: new Date().toISOString(), message: "Posible documento escaneado. OCR no está disponible." } : f)); return;
      }
      const parsed = parseInvoice(result.text, target.name);
      setLines((old) => [...old.filter((l) => l.fileName !== target.name), ...parsed.lines]);
      const needsReview = parsed.lines.some((l) => l.status === "Revisión requerida");
      setFiles((old) => old.map((f) => f.id === target.id ? { ...f, file: undefined, pages: result.pages, status: needsReview ? "Revisión requerida" : "Procesado", processedAt: new Date().toISOString(), message: `${parsed.lines.length} línea(s) detectada(s)`, text: result.text.slice(0, 100000), header: parsed.header } : f));
    } catch (error) {
      if (error instanceof DOMException && error.name === "AbortError") { setFiles((old) => old.map((f) => f.id === target.id ? { ...f, status: "Pendiente", message: "Procesamiento cancelado." } : f)); return; }
      const message = error instanceof Error ? error.message : "No se pudo leer el archivo.";
      setFiles((old) => old.map((f) => f.id === target.id ? { ...f, status: "Error", processedAt: new Date().toISOString(), message } : f));
    }
  }

  async function processFiles() {
    const queue = files.filter((f) => ["Pendiente", "Error"].includes(f.status) && f.file);
    if (!queue.length) { setNotice("No hay facturas pendientes disponibles para procesar."); return; }
    setProcessing(true); const controller = new AbortController(); abortRef.current = controller;
    let cursor = 0;
    const worker = async () => { while (cursor < queue.length && !controller.signal.aborted) { const item = queue[cursor]; cursor += 1; await processOne(item, controller.signal); await new Promise((resolve) => setTimeout(resolve, 0)); } };
    await Promise.all(Array.from({ length: Math.min(concurrency, queue.length) }, worker));
    setProcessing(false); abortRef.current = undefined;
  }

  async function loadInventory(file: File) {
    try { const book = await readInventoryFile(file); if (!book.rows.length) throw new Error("La hoja seleccionada está vacía."); setInventoryBook(book); const guessed = autoMap(book.headers); setMapping(guessed); setInventory(guessed.description && guessed.quantity ? mapInventory(book.rows, guessed) : []); setNotice("Inventario cargado. Verifique el mapeo de columnas."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo leer el inventario."); }
  }
  function applyMapping(next: ColumnMapping) { setMapping(next); setInventory(next.description && next.quantity && inventoryBook ? mapInventory(inventoryBook.rows, next) : []); }
  function selectInventorySheet(sheetName: string) {
    if (!inventoryBook?.sheets) return;
    const rows = inventoryBook.sheets[sheetName] ?? [];
    const next = { ...inventoryBook, selectedSheet: sheetName, rows, headers: rows.length ? Object.keys(rows[0]) : [] };
    setInventoryBook(next); const guessed = autoMap(next.headers); setMapping(guessed); setInventory(guessed.description && guessed.quantity ? mapInventory(rows, guessed) : []);
    if (!rows.length) setNotice("La hoja seleccionada está vacía.");
  }
  function editLine(id: string, field: keyof InvoiceLine, value: string) {
    setLines((old) => old.map((line) => { if (line.id !== id) return line; const numeric = ["quantity", "unitPrice", "tax", "lineTotal"].includes(field); const parsed = numeric ? parseLocaleNumber(value) : {}; const next = { ...line, [field]: numeric ? parsed.value : value }; const invalid = !next.description.trim() || next.quantity === undefined || next.unitPrice === undefined || next.lineTotal === undefined; return { ...next, status: invalid ? "Revisión requerida" : next.status, observation: parsed.warning ?? next.observation } as InvoiceLine; }));
  }

  function loadDemo() {
    const demoLines: InvoiceLine[] = [
      { id: uid(), fileName: "factura_001.pdf", invoiceNumber: "F-001", date: "2026-07-01", supplier: "Distribuidora Central", code: "ARR-001", description: "Arroz 1 kg", quantity: 10, unitPrice: 950, tax: 0, lineTotal: 9500, status: "Válido", observation: "" },
      { id: uid(), fileName: "factura_002.pdf", invoiceNumber: "F-002", date: "2026-07-04", supplier: "Abastecedora Norte", code: "ARR-001", description: "ARROZ 1 KG", quantity: 5, unitPrice: 980, tax: 0, lineTotal: 4900, status: "Válido", observation: "" },
      { id: uid(), fileName: "factura_002.pdf", invoiceNumber: "F-002", date: "2026-07-04", supplier: "Abastecedora Norte", code: "CAF-250", description: "Café molido 250 g", quantity: 8, unitPrice: 2400, tax: 2496, lineTotal: 21696, status: "Válido", observation: "" },
      { id: uid(), fileName: "factura_003.pdf", invoiceNumber: "F-003", date: "2026-07-08", supplier: "Suministros Demo", code: "ACE-1L", description: "Aceite vegetal 1 l", quantity: 4, unitPrice: 1900, tax: 0, lineTotal: 7600, status: "Válido", observation: "" },
      { id: uid(), fileName: "factura_003.pdf", invoiceNumber: "F-003", date: "2026-07-08", supplier: "Suministros Demo", code: "", description: "Producto por validar", quantity: undefined, unitPrice: 500, lineTotal: undefined, status: "Revisión requerida", observation: "Cantidad y total pendientes." },
    ];
    setFiles(["factura_001.pdf", "factura_002.pdf", "factura_003.pdf"].map((name, i) => ({ id: uid(), name, size: 0, pages: 1, status: i === 2 ? "Revisión requerida" : "Procesado", processedAt: new Date().toISOString(), message: "Datos de demostración", header: { invoiceNumber: `F-00${i + 1}`, date: `2026-07-0${i + 1}`, supplier: ["Distribuidora Central", "Abastecedora Norte", "Suministros Demo"][i], currency: "CRC", total: demoLines.filter((l) => l.fileName === name).reduce((n, l) => n + (l.lineTotal ?? 0), 0) } })));
    setLines(demoLines);
    const rows = [{ Código: "ARR-001", Descripción: "Arroz 1kg", Cantidad: 15, Costo: 960 }, { Código: "CAF-250", Descripción: "Café molido 250 g", Cantidad: 5, Costo: 2350 }, { Código: "ACE-1L", Descripción: "Aceite vegetal 1 l", Cantidad: 7, Costo: 1850 }, { Código: "SAL-500", Descripción: "Sal 500 g", Cantidad: 20, Costo: 450 }];
    const book = { name: "inventario_demo.xlsx", sheetNames: ["Inventario"], selectedSheet: "Inventario", rows, headers: Object.keys(rows[0]), sheets: { Inventario: rows } }; setInventoryBook(book); const map = { code: "Código", description: "Descripción", quantity: "Cantidad", cost: "Costo" }; setMapping(map); setInventory(mapInventory(rows, map)); setNotice("Datos ficticios cargados: incluye coincidencia, faltante, sobrante, no encontrado y revisión.");
  }

  const visibleLines = lines.filter((l) => (!filter || `${l.code} ${l.description}`.toLowerCase().includes(filter.toLowerCase())) && (!statusFilter || l.status === statusFilter) && (!fileFilter || l.fileName === fileFilter));
  const exportData = (partial: boolean) => { if (!mode) return; const exportMode = mode === "excel" && !inventoryBook ? "analyze" : mode; try { exportAuditReport({ summary, comparisons: exportMode === "analyze" ? [] : comparisons, consolidated, lines, files, inventory: exportMode === "excel" ? inventoryBook : undefined, partial, tolerance, mode: exportMode }); } catch { setNotice("Ocurrió un error al generar el archivo Excel."); } };
  const newAudit = () => { setFiles([]); setLines([]); setInventoryBook(undefined); setInventory([]); setMapping({ code: "", description: "", quantity: "", cost: "" }); setManualCounts({}); setShowFinal(false); setMode(null); setNotice(""); };

  if (!mode) return <main className="grid min-h-screen place-items-center bg-[#f3f7f6] px-6 py-12"><div className="w-full max-w-5xl"><div className="mb-10 text-center"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-2xl bg-teal-700 text-2xl font-black text-white shadow-lg">AIQ</div><h1 className="text-5xl font-black tracking-tight text-[#123a35]">AuditIQ</h1><p className="mt-3 text-lg font-medium text-slate-500">Smart Inventory Audits</p></div><div className="grid gap-5 md:grid-cols-3">{[
    { id: "analyze" as const, icon: <FileText size={26}/>, title: "Analizar facturas", description: "Procesa las facturas y genera un consolidado de productos y montos sin realizar comparaciones." },
    { id: "excel" as const, icon: <FileSpreadsheet size={26}/>, title: "Comparar con inventario", description: "Procesa las facturas y las compara automáticamente contra un inventario en Excel." },
    { id: "manual" as const, icon: <CheckCircle2 size={26}/>, title: "Capturar inventario manualmente", description: "Procesa las facturas y permite ingresar manualmente el conteo físico para calcular diferencias." },
  ].map((option) => <Card key={option.id} className="flex min-h-72 flex-col p-6 transition hover:-translate-y-1 hover:border-teal-300 hover:shadow-lg"><div className="mb-5 grid h-12 w-12 place-items-center rounded-xl bg-teal-50 text-teal-700">{option.icon}</div><h2 className="text-xl font-bold">{option.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{option.description}</p><Button className="mt-6 w-full" onClick={() => setMode(option.id)}>Iniciar</Button></Card>)}</div><p className="mt-8 text-center text-xs text-slate-500">Procesamiento local y privado. Sus documentos no salen del navegador.</p></div></main>;

  if (showFinal) {
    const differences = comparisons.filter((r) => ["Faltante", "Sobrante", "No encontrado"].includes(r.status)).length;
    return <main className="grid min-h-screen place-items-center bg-[#f3f7f6] px-6 py-12"><Card className="w-full max-w-3xl overflow-hidden"><div className="bg-[#123a35] p-8 text-center text-white"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-full bg-emerald-400/20"><CheckCircle2 size={32} className="text-emerald-300"/></div><h1 className="text-3xl font-black">Auditoría completada</h1><p className="mt-2 text-teal-100">AuditIQ · Smart Inventory Audits</p></div><div className="p-8"><div className="grid gap-3 sm:grid-cols-2">{[["Facturas procesadas", summary.processedCount], ["Productos encontrados", summary.extractedProducts], ["Productos consolidados", summary.consolidatedProducts], ["Total facturado", money(summary.billedTotal, currency)], ["Diferencias encontradas", differences]].map(([label, value]) => <div key={String(label)} className="flex items-center gap-3 rounded-lg bg-slate-50 p-4"><CheckCircle2 size={20} className="text-emerald-600"/><div><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{value}</p></div></div>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={() => exportData(false)}><Download size={16}/>Descargar Excel</Button><Button kind="secondary" onClick={newAudit}><RefreshCw size={16}/>Nueva auditoría</Button></div></div></Card></main>;
  }

  return <main className="min-h-screen">
    <header className="border-b border-teal-900/10 bg-[#123a35] text-white"><div className="mx-auto max-w-[1500px] px-6 py-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[.18em] text-teal-200">{mode === "analyze" ? "Análisis de facturas" : mode === "manual" ? "Conteo físico manual" : "Comparación con inventario"}</p><h1 className="text-3xl font-black tracking-tight">AuditIQ</h1><p className="mt-2 text-teal-50">Smart Inventory Audits</p></div><div className="flex gap-2"><Button kind="secondary" onClick={loadDemo}><RefreshCw size={16}/>Cargar datos de demostración</Button><Button kind="secondary" onClick={newAudit}>Cambiar modo</Button></div></div><div className="mt-7 flex items-center gap-3 rounded-lg border border-teal-500/30 bg-teal-950/30 px-4 py-3 text-sm text-teal-50"><ShieldCheck size={20} className="shrink-0 text-teal-300"/>Los documentos se procesan localmente en este navegador y no se almacenan en servidores.</div></div></header>
    <div className="mx-auto max-w-[1500px] space-y-6 px-6 py-7">
      {notice && <div className="flex items-center justify-between rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><span className="flex items-center gap-2"><AlertTriangle size={17}/>{notice}</span><button aria-label="Cerrar aviso" onClick={() => setNotice("")}><XCircle size={18}/></button></div>}
      <nav className={`grid grid-cols-2 gap-2 ${mode === "analyze" ? "md:grid-cols-4" : "md:grid-cols-6"}`}>{(mode === "analyze" ? ["Cargar facturas", "Procesar", "Revisar datos", "Descargar"] : mode === "manual" ? ["Cargar facturas", "Procesar", "Revisar datos", "Conteo manual", "Resumen", "Descargar"] : ["Cargar facturas", "Cargar inventario", "Procesar", "Revisar datos", "Comparar", "Descargar"]).map((step, index) => <div key={step} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-700"><span className="grid h-7 w-7 place-items-center rounded-full bg-teal-50 text-teal-800">{index + 1}</span>{step}</div>)}</nav>

      <div className={`grid gap-6 ${mode === "excel" ? "xl:grid-cols-2" : ""}`}>
        <Card><div className="border-b border-slate-200 p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><FileText className="text-teal-700"/>1. Cargar facturas PDF</h2><p className="mt-1 text-sm text-slate-500">Seleccione hasta 200 documentos. Límite recomendado: 50 MB por archivo.</p></div><div className="p-5"><input ref={pdfInput} hidden type="file" accept=".pdf,application/pdf" multiple onChange={(e) => { selectPdfs(e.target.files); e.target.value = ""; }}/><div className="flex flex-wrap gap-2"><Button onClick={() => pdfInput.current?.click()}><Upload size={16}/>Seleccionar facturas</Button><Button kind="secondary" onClick={processFiles} disabled={processing || !files.some((f) => ["Pendiente", "Error"].includes(f.status) && f.file)}><Play size={16}/>Procesar facturas</Button><Button kind="secondary" onClick={() => abortRef.current?.abort()} disabled={!processing}><XCircle size={16}/>Cancelar</Button><Button kind="danger" onClick={() => { setFiles([]); setLines([]); }} disabled={processing || !files.length}><Trash2 size={16}/>Limpiar</Button></div><div className="mt-4 max-h-64 space-y-2 overflow-auto">{files.length === 0 ? <p className="rounded-lg border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Aún no hay facturas seleccionadas.</p> : files.map((file) => <details key={file.id} className="rounded-lg border border-slate-200"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-3 py-2.5"><div className="min-w-0"><p className="truncate text-sm font-semibold">{file.name}</p><p className="text-xs text-slate-500">{formatSize(file.size)}{file.pages ? ` · ${file.pages} pág.` : ""}{file.message ? ` · ${file.message}` : ""}</p></div><div className="flex shrink-0 items-center gap-2"><Badge>{file.status}</Badge><button aria-label="Eliminar archivo" onClick={(e) => { e.preventDefault(); setFiles((old) => old.filter((f) => f.id !== file.id)); setLines((old) => old.filter((l) => l.fileName !== file.name)); }}><Trash2 size={15}/></button><ChevronDown size={15}/></div></summary>{file.text && <pre className="max-h-52 overflow-auto whitespace-pre-wrap border-t bg-slate-50 p-3 text-xs">{file.text}</pre>}</details>)}</div></div></Card>

      {mode === "excel" && <Card><div className="border-b border-slate-200 p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><FileSpreadsheet className="text-teal-700"/>2. Cargar inventario</h2><p className="mt-1 text-sm text-slate-500">Opcional. Formatos admitidos: XLSX, XLS y CSV.</p></div><div className="space-y-4 p-5"><input ref={inventoryInput} hidden type="file" accept=".xlsx,.xls,.csv" onChange={(e) => e.target.files?.[0] && loadInventory(e.target.files[0])}/><Button onClick={() => inventoryInput.current?.click()}><Upload size={16}/>Seleccionar inventario</Button>{inventoryBook && <><div className="rounded-lg bg-teal-50 p-3 text-sm text-teal-900"><b>{inventoryBook.name}</b> · {inventoryBook.rows.length} filas</div>{inventoryBook.sheetNames.length > 1 && <label className="block text-xs font-semibold text-slate-600">Hoja del inventario<select className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm" value={inventoryBook.selectedSheet} onChange={(e) => selectInventorySheet(e.target.value)}>{inventoryBook.sheetNames.map((name) => <option key={name}>{name}</option>)}</select></label>}<div className="grid grid-cols-2 gap-3">{(["code", "description", "quantity", "cost"] as const).map((key) => <label key={key} className="text-xs font-semibold text-slate-600">{({ code: "Código (opcional)", description: "Descripción *", quantity: "Cantidad *", cost: "Costo (opcional)" })[key]}<select className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm" value={mapping[key]} onChange={(e) => applyMapping({ ...mapping, [key]: e.target.value })}><option value="">No seleccionar</option>{inventoryBook.headers.map((h) => <option key={h}>{h}</option>)}</select></label>)}</div>{(!mapping.description || !mapping.quantity) && <p className="text-sm font-semibold text-red-700">Seleccione las columnas de descripción y cantidad para comparar.</p>}<div className="table-scroll max-h-44"><table><thead><tr>{inventoryBook.headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{inventoryBook.rows.slice(0, 20).map((r, i) => <tr key={i}>{inventoryBook.headers.map((h) => <td key={h}>{String(r[h] ?? "")}</td>)}</tr>)}</tbody></table></div></>}</div></Card>}
      </div>

      <Card><div className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><div><h2 className="text-lg font-bold">3. Procesamiento por lotes</h2><p className="text-sm text-slate-500">La cola continúa aunque un archivo falle.</p></div><label className="text-sm font-semibold">Concurrencia <select className="ml-2 rounded-lg border p-2" value={concurrency} onChange={(e) => setConcurrency(Math.min(5, Math.max(1, Number(e.target.value))))}>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label></div><div className="p-5"><div className="mb-3 flex justify-between text-sm"><span>{processing ? <span className="inline-flex items-center gap-2 font-semibold text-teal-800"><LoaderCircle size={16} className="animate-spin"/>Procesando {files.find((f) => f.status === "Procesando")?.name ?? "facturas"}</span> : `${completed} de ${files.length} facturas completadas`}</span><b>{progress}%</b></div><div className="h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-teal-600 transition-all" style={{ width: `${progress}%` }}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-center md:grid-cols-5">{[["Total", files.length], ["Pendientes", files.filter((f) => f.status === "Pendiente").length], ["Procesadas", summary.processedCount], ["Con error", summary.errorCount], ["Revisión", files.filter((f) => f.status === "Revisión requerida").length]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-3"><b className="block text-xl">{value}</b><span className="text-xs text-slate-500">{label}</span></div>)}</div></div></Card>

      <Card><div className="border-b p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">4. Revisar datos extraídos</h2><p className="text-sm text-slate-500">Edite cualquier celda antes de consolidar.</p></div><Button onClick={() => setLines((old) => [...old, { id: uid(), fileName: "Manual", invoiceNumber: "", date: "", supplier: "", code: "", description: "", status: "Revisión requerida", observation: "Fila agregada manualmente." }])}><Plus size={16}/>Agregar fila</Button></div><div className="mt-4 grid gap-2 md:grid-cols-3"><input className="rounded-lg border p-2.5 text-sm" placeholder="Buscar código o descripción" value={filter} onChange={(e) => setFilter(e.target.value)}/><select className="rounded-lg border p-2.5 text-sm" value={fileFilter} onChange={(e) => setFileFilter(e.target.value)}><option value="">Todos los archivos</option>{[...new Set(lines.map((l) => l.fileName))].map((f) => <option key={f}>{f}</option>)}</select><select className="rounded-lg border p-2.5 text-sm" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">Todos los estados</option><option>Válido</option><option>Revisión requerida</option></select></div></div><div className="table-scroll"><table><thead><tr>{["Archivo","N.º factura","Fecha","Proveedor","Código","Descripción","Cantidad","Precio","Impuesto","Total línea","Estado","Observación","Acciones"].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{visibleLines.map((line) => <tr key={line.id}>{(["fileName","invoiceNumber","date","supplier","code","description","quantity","unitPrice","tax","lineTotal","observation"] as (keyof InvoiceLine)[]).map((field, index) => index === 10 ? null : <td key={field}><input aria-label={field} value={String(line[field] ?? "")} onChange={(e) => editLine(line.id, field, e.target.value)}/></td>)}<td><Badge>{line.status}</Badge></td><td><input value={line.observation} onChange={(e) => editLine(line.id, "observation", e.target.value)}/></td><td><div className="flex gap-1"><button title="Marcar como revisado" onClick={() => setLines((old) => old.map((l) => l.id === line.id ? { ...l, status: "Válido", observation: "Revisado manualmente." } : l))}><CheckCircle2 size={17} className="text-emerald-700"/></button><button title="Duplicar" onClick={() => setLines((old) => [...old, { ...line, id: uid() }])}><Plus size={17}/></button><button title="Eliminar" onClick={() => setLines((old) => old.filter((l) => l.id !== line.id))}><Trash2 size={17} className="text-red-600"/></button></div></td></tr>)}</tbody></table></div></Card>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Facturas procesadas", summary.processedCount], ["Productos únicos", summary.consolidatedProducts], ["Total de unidades", summary.billedUnits], ["Valor total facturado", money(summary.billedTotal, currency)], ...(mode !== "analyze" ? [["Coincidencias", summary.matches], ["Faltantes", summary.shortages], ["Sobrantes", summary.surpluses]] : [])].map(([label, value]) => <Card key={String(label)} className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></Card>)}</div>

      <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Card><div className="border-b p-5"><h2 className="text-lg font-bold">Productos consolidados</h2><p className="text-sm text-slate-500">Vista unificada por código o descripción normalizada.</p></div><div className="table-scroll max-h-80"><table><thead><tr>{["Código","Producto","Cantidad total","Precio promedio","Total facturado","Facturas"].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{consolidated.map((p) => <tr key={p.key}><td>{p.code || "—"}</td><td>{p.description}</td><td>{p.billedQuantity}</td><td>{money(p.averagePrice, currency)}</td><td>{money(p.billedTotal, currency)}</td><td>{p.invoiceCount}</td></tr>)}</tbody></table></div></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 font-black text-violet-700">IQ</div><div><h2 className="font-bold">AuditIQ Insights</h2><p className="text-xs text-slate-500">Observaciones basadas en reglas</p></div></div><ul className="mt-5 space-y-3">{insights.map((item) => <li key={item} className="flex gap-2 rounded-lg bg-slate-50 p-3 text-sm leading-5 text-slate-700"><AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-600"/>{item}</li>)}</ul></Card></div>

      {mode !== "analyze" && <Card><div className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><div><h2 className="text-lg font-bold">{mode === "manual" ? "Conteo físico manual" : "5. Comparar inventario"}</h2><p className="text-sm text-slate-500">Diferencia = cantidad inventario − cantidad facturada.</p></div>{mode === "excel" && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={includeOnlyInventory} onChange={(e) => setIncludeOnlyInventory(e.target.checked)}/>Incluir productos solo en inventario</label>}</div><div className="table-scroll"><table><thead><tr>{(mode === "manual" ? ["Código","Producto","Cantidad facturada","Conteo físico","Diferencia","Estado"] : ["Código","Producto","Cant. facturada","Cant. inventario","Diferencia","Precio promedio","Total facturado","Estado","Método","Observación"]).map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{comparisons.map((r) => mode === "manual" ? <tr key={r.id}><td>{r.code || "—"}</td><td>{r.product}</td><td>{r.billedQuantity}</td><td><input className="w-32 rounded-lg border border-slate-300 bg-white p-2" aria-label={`Conteo físico de ${r.product}`} type="number" value={manualCounts[r.id] ?? ""} onChange={(e) => setManualCounts((old) => ({ ...old, [r.id]: e.target.value === "" ? undefined : Number(e.target.value) }))}/></td><td className="font-bold">{r.difference ?? "—"}</td><td><Badge>{r.status}</Badge></td></tr> : <tr key={r.id}><td>{r.code}</td><td>{r.product}</td><td>{r.billedQuantity}</td><td>{r.inventoryQuantity ?? "—"}</td><td>{r.difference ?? "—"}</td><td>{money(r.averagePrice, currency)}</td><td>{money(r.billedTotal, currency)}</td><td><Badge>{r.status}</Badge></td><td>{r.matchMethod}</td><td>{r.observation}</td></tr>)}</tbody></table></div><div className="flex flex-wrap gap-3 border-t p-4">{(["Coincide","Faltante","Sobrante","No encontrado","Solo en inventario","Revisión requerida"] as ComparisonStatus[]).map((s) => <Badge key={s}>{s}</Badge>)}</div></Card>}

      <Card><div className="border-b p-5"><h2 className="text-lg font-bold">Resumen por factura</h2><div className="mt-3 flex flex-wrap gap-4"><label className="text-sm">Tolerancia <input className="ml-2 w-24 rounded border p-2" type="number" value={tolerance} onChange={(e) => setTolerance(Number(e.target.value))}/></label><label className="text-sm">Moneda <select className="ml-2 rounded border p-2" value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="CRC">CRC</option><option value="USD">USD</option><option value="none">Sin símbolo</option></select></label></div></div><div className="table-scroll"><table><thead><tr>{["Archivo","N.º factura","Fecha","Proveedor","Productos","Unidades","Subtotal","Impuesto","Total detectado","Total calculado","Diferencia","Estado"].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{files.map((f) => { const rows = lines.filter((l) => l.fileName === f.name); const calc = rows.reduce((n,l) => n + (l.lineTotal ?? 0), 0); const diff = f.header?.total === undefined ? undefined : f.header.total - calc; const state = diff !== undefined && Math.abs(diff) > tolerance ? "Revisión requerida" : f.status; return <tr key={f.id}><td>{f.name}</td><td>{f.header?.invoiceNumber}</td><td>{f.header?.date}</td><td>{f.header?.supplier}</td><td>{rows.length}</td><td>{rows.reduce((n,l) => n + (l.quantity ?? 0),0)}</td><td>{money(f.header?.subtotal ?? 0,currency)}</td><td>{money(f.header?.taxes ?? 0,currency)}</td><td>{money(f.header?.total ?? 0,currency)}</td><td>{money(calc,currency)}</td><td>{diff ?? "—"}</td><td><Badge>{state}</Badge></td></tr>; })}</tbody></table></div></Card>

      <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-5"><div><h2 className="text-lg font-bold">6. Descargar reporte</h2><p className="mt-1 text-sm text-slate-500">El contenido del Excel se adapta automáticamente al modo de auditoría seleccionado.</p></div><div className="flex flex-wrap gap-2"><Button kind="secondary" onClick={() => exportData(true)} disabled={!files.length && !lines.length}><Download size={16}/>Descargar avance</Button><Button onClick={() => exportData(false)} disabled={!lines.length}><Download size={16}/>Descargar Excel</Button><Button kind="secondary" onClick={() => setShowFinal(true)} disabled={!lines.length}><CheckCircle2 size={16}/>Finalizar auditoría</Button></div></div></Card>

      <Card className="p-6"><h2 className="font-bold">Limitaciones de esta versión</h2><ul className="mt-3 grid list-disc gap-2 pl-5 text-sm text-slate-600 md:grid-cols-2"><li>Solo se procesan PDFs con texto seleccionable.</li><li>Los PDFs escaneados requieren revisión manual.</li><li>Los formatos de factura pueden variar.</li><li>Los resultados deben ser validados por el auditor.</li><li>Los documentos no se almacenan en servidores.</li><li>No incluye OCR ni coincidencias aproximadas agresivas.</li></ul></Card>
    </div>
  </main>;
}
